
enum Command{
	SENDHOSTNAME,
	CLOSECONNECTION,
	REFRESHTEXT,
	CREATENEWHOSTNAME,
	REQUESTACCEPT,
	ACCEPT,
	DENY,
	CONNECTIONESTABLISHED,
	INVALIDEREQUEST,
	INVALIDRESPONS,
	MESSAGERECIVED,
	ACOMPLISHMENT;
}